version: '3'

services:

  frontend:
    container_name: chatfly
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 7079:7079
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run start dev