version: '3.7'

services:

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 7079:7079
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start